permissions:
  id-token: write # Required to request a JWT token

on: [push]
  
jobs:
  function_version_deployment_job:
    runs-on: ubuntu-latest
    name: Function redeployment job
    steps:
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core @actions/http-client
      # Getting the workflow task token
      - name: Get Id Token
        uses: actions/github-script@v7
        id: tokenid
        with:
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken()
            coredemo.setOutput('id_token', id_token)
      # Exchanging the workflow task token for an IAM token of a service account in Yandex Cloud
      - name: GetIAMToken
        run: |
          SA_ID="<service_account_ID>"
          IAMTOKEN=$(curl -sH "Content-Type: application/x-www-form-urlencoded" -d "grant_type=urn:ietf:params:oauth:grant-type:token-exchange&requested_token_type=urn:ietf:params:oauth:token-type:access_token&audience=$SA_ID&subject_token=${{steps.tokenid.outputs.id_token}}&subject_token_type=urn:ietf:params:oauth:token-type:id_token" -X POST https://auth.yandex.cloud/oauth/token | jq -r '.access_token')
          echo "IAMToken=${IAMTOKEN}" >> $GITHUB_OUTPUT
        id: IAMtoken
      
      - name: Trigger function redeployment step
        id: redeployment
        uses: ilyashikalov/yc-actions@main
        with:
          function-id: 'd4e3iua9srqpkh0et7gr'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.redeployment.outputs.time }}"
