on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Function redeployment job
    steps:
      - name: Trigger function redeployment step
        id: redeployment
        uses: ilyashikalov/yc-actions@main
        with:
          function-id: 'd4e3iua9srqpkh0et7gr'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
